// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'your-apiKey',
      appId: 'your-appId',
      messagingSenderId: 'your-messagingSenderId',
      projectId: 'your-projectId',
      authDomain: 'your-authDomain',
      storageBucket: 'your-storageBucket',
      measurementId: 'your-measurementId',
      databaseURL: 'your-databaseURL'
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'your-apiKey',
      appId: 'your-appId',
      messagingSenderId: 'your-messagingSenderId',
      projectId: 'your-projectId',
      storageBucket: 'your-storageBucket',
      databaseURL: 'your-databaseURL'
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'your-apiKey',
      appId: 'your-appId',
      messagingSenderId: 'your-messagingSenderId',
      projectId: 'your-projectId',
      storageBucket: 'your-storageBucket',
      iosClientId: 'your-iosClientId',
      iosBundleId: 'your-iosBundleId',
      databaseURL: 'your-databaseURL'
  );
}